# Generated by Django 3.0.2 on 2020-01-21 13:09

import cheque.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chequeAmount', models.CharField(help_text='Сумма чека*', max_length=200, verbose_name='На какую сумму у вас есть чек?')),
                ('chequeDate', models.CharField(help_text='Дата совершения покупки', max_length=100)),
                ('chequeThing', models.CharField(help_text='Товар*', max_length=200, verbose_name='Вещи которые вы купили')),
                ('shop', models.IntegerField(default=1, help_text='Откуда вы купили товар?', verbose_name='Магазин')),
                ('date', models.DateTimeField(default=cheque.models.Post.default_datetime, verbose_name='Дата добавления чека')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
