# Generated by Django 3.0.2 on 2020-02-14 13:45

import cheque.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ref',
            field=models.CharField(default=cheque.models.Post.default_datetime, max_length=200, verbose_name='Ссылка на покупателя'),
        ),
        migrations.AlterField(
            model_name='post',
            name='chequeThing',
            field=models.CharField(help_text='Товар*', max_length=200, verbose_name='Вещи которые вы купили?'),
        ),
    ]
