# Generated by Django 3.0.2 on 2020-02-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0002_auto_20200214_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='check',
            field=models.BooleanField(default=True, verbose_name='proverka'),
        ),
        migrations.AlterField(
            model_name='post',
            name='chequeAmount',
            field=models.CharField(help_text='Сумма чека', max_length=200, verbose_name='На какую сумму у вас есть чек?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='chequeDate',
            field=models.CharField(help_text='Дата покупки указанная в чеке', max_length=100, verbose_name='Дата совершения покупки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='chequeThing',
            field=models.CharField(help_text='Товар', max_length=200, verbose_name='Вещи которые вы купили?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ref',
            field=models.CharField(max_length=200, verbose_name='Ссылка на покупателя'),
        ),
        migrations.AlterField(
            model_name='post',
            name='shop',
            field=models.CharField(help_text='Откуда вы купили товар?', max_length=200, verbose_name='Магазин'),
        ),
    ]
